# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 20:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('htme_url', models.URLField(max_length=400)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(help_text='Date when this repository was created')),
                ('last_api_consult', models.DateTimeField(auto_now_add=True)),
                ('last_commit', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
            },
        ),
    ]
